# fly.toml app configuration file generated for bytehackz2023bot2 on 2023-11-12T12:45:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bytehackz2023bot2"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]